### PR TITLE
Quite a few 512x374 (USA) image updates.

### PR DESCRIPTION
**Pull request by HarryTheTurtle**
Almost complete updated 512x374 N64 (USA) images. Only missing a couple. Would like to see region specific downloadable zips in the future.

I overhauled the (USA) N64 box art to 512x374px and created a USA specific repository on my profile if you need to use any images or use the entire repository for region specifics in the future. I fixed some of the box arts by removing blemishes, damage, and stickers.

### CODE REVIEW

**Comment by HarryTheTurtle** [comment]
Anyone know why those two files are conflicting? Not sure how to fix it without simply deleting them.

**Comment by RobLoach** [comment]
Looks like two files are conflicting.... Mind fixing it up? If not, we could fix it later on. Thanks1

**Comment by HarryTheTurtle** [comment]
Hey Rob Im not entirely certain how to fix the conflict.

**Comment by HarryTheTurtle** [comment]
I'm going to close this re-upload the entirety of my repository using the command line. Should correct any issues hopefully.

**Pull request closed without merging**
