### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by MarcoEstevez**
1. Set the actual PAL region art for wave racer
2. Improve  Wonder Project J2
3. Paper Mario updates

### CODE REVIEW

**Comment by HarryTheTurtle** [comment]
Hey Marco I was wondering if I could revert back the Paper Mario update. The Paper Mario art is SUPER over saturated. It makes the colors pop out but it kinda hurts to look at. Haha. Please allow me to compare the original box art with the image in this PR...

Here is the updated image from this PR. This is honestly really hard to look at because of the saturation. Mairo looks like he has joundice.

Paper Mario (USA)


Here is the original upload. I would like to point out that this is an unedited, actual scan, of the box art itself.

Paper Mario (USA) (1)


And here is another picture of the box art I just pulled off the internet.

origbox


Just for reference, here is the scanned box art I used.

n64_papermario


When comparing the images you can see that the N64 logo on your updated image has such a high contrast that the colors are solid green on blue. Where in the original box art they are light and not a solid. Also koopas shell is so over saturated that you can no longer distinguish the fine lines that separate sections on his shell which is an indicator of over saturation.

There are a lot of images on the web where the box art for Paper Mario is over saturated so I see where you got the idea that it is supposed to be that saturated. If you all like the saturated version I won't protest anymore. But I would like to see us keep the box arts as close to the originals as possible.

**Comment by MarcoEstevez** [comment]
Well... I see your point, personally I don't have a clear answer here.

In one side I kind of agree with you, the non saturated version might match better with the original print, so for those people familiar with the real release this one might be better.

In the other side, the over saturated pic tends to hide traces of a 2 decades old paper print and pretends be more "digital".

At the end of the day this subject is tied to personal preferences, nostalgia vs sharpen and contrasted clear images.

Personally I do prefer mine :-P cause It looks pretty on XMB menu, which has quite digital modern UI style, but as i said,that's only me.

I feel we might need to take a decision here on what we are aiming for.... accuracy or prettiness

@RobLoach what's your opinion here?

**Comment by HarryTheTurtle** [comment]
Yeah I agree the box art does look a bit sun bleached when displayed on the XMB. Especially when the background color is black.

What about this version? I've increased the old Paper Mario contrast by +64 and decreased brightness -22.
Paper Mario (USA)

Will you try this one and see if it pops for you? Maybe we can meet in the middle here.

**Comment by MarcoEstevez** [comment]
Looking good, please feel free to create a PR  :-D

**Pull request merged**
