### PR TITLE
Fixed game plus updates to others

### PR DESCRIPTION
**Pull request by omegamustard**

### CODE REVIEW

**Review by RobLoach — CHANGES_REQUESTED** [review]
@omegamustard These look great! Would you be able to remove the black borders around some of the titles and snaps?

**Comment by ghost** [comment]
Not sure the smartest way to do this, but I cropped all these files. I can just add them in another pull request, if you just want to go ahead and merge this one? Aidyn Chronicles will become a symbolic link anyways. @RobLoach 
64 Oozumou (Japan)
64 Oozumou 2 (Japan)
64 Trump Collection - Alice no Wakuwaku Trump World (Japan)
Aidyn Chronicles - The First Mage (USA)
64 Oozumou (Japan)
64 Trump Collection - Alice no Wakuwaku Trump World (Japan)
Aidyn Chronicles - The First Mage (Europe)

**Comment by RobLoach** [comment]
These are looking great! I can help out on a few of them too. Some can be tricky :+1:

**Comment by ghost** [comment]
I've got the rest of them cropped. I just didn't know how you wanted them uploaded since this isn't my PR. No sense in seeing the same image 5-6 times

**Comment by omegamustard** [comment]
Those look fine. I haven’t had a chance to update them. So those will work until I can get updated ones.


Sent from Yahoo Mail for iPhone


On Friday, June 24, 2022, 9:16 AM, masanasake ***@***.***> wrote:




Not sure the smartest way to do this, but I cropped all these files. I can just add them in another pull request, if you just want to go ahead and merge this one? Aidyn Chronicles will become a symbolic link anyways.

**Comment by ghost** [comment]
I put the cropped versions in with my clean-up PR, so there's no action necessary if you don't feel like re-taking them. This had been open for awhile, so I didn't want your work to go to waste.

**Pull request merged**
